/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/toniebox.pb.freshness-check.fc-request.proto */

#ifndef PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2drequest_2eproto__INCLUDED
#define PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2drequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct TonieFreshnessCheckRequest TonieFreshnessCheckRequest;
typedef struct TonieFCInfo TonieFCInfo;


/* --- enums --- */


/* --- messages --- */

struct  TonieFreshnessCheckRequest
{
  ProtobufCMessage base;
  size_t n_tonie_infos;
  TonieFCInfo **tonie_infos;
};
#define TONIE_FRESHNESS_CHECK_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tonie_freshness_check_request__descriptor) \
, 0,NULL }


struct  TonieFCInfo
{
  ProtobufCMessage base;
  uint64_t uid;
  uint32_t audio_id;
};
#define TONIE_FCINFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tonie_fcinfo__descriptor) \
, 0, 0 }


/* TonieFreshnessCheckRequest methods */
void   tonie_freshness_check_request__init
                     (TonieFreshnessCheckRequest         *message);
size_t tonie_freshness_check_request__get_packed_size
                     (const TonieFreshnessCheckRequest   *message);
size_t tonie_freshness_check_request__pack
                     (const TonieFreshnessCheckRequest   *message,
                      uint8_t             *out);
size_t tonie_freshness_check_request__pack_to_buffer
                     (const TonieFreshnessCheckRequest   *message,
                      ProtobufCBuffer     *buffer);
TonieFreshnessCheckRequest *
       tonie_freshness_check_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tonie_freshness_check_request__free_unpacked
                     (TonieFreshnessCheckRequest *message,
                      ProtobufCAllocator *allocator);
/* TonieFCInfo methods */
void   tonie_fcinfo__init
                     (TonieFCInfo         *message);
size_t tonie_fcinfo__get_packed_size
                     (const TonieFCInfo   *message);
size_t tonie_fcinfo__pack
                     (const TonieFCInfo   *message,
                      uint8_t             *out);
size_t tonie_fcinfo__pack_to_buffer
                     (const TonieFCInfo   *message,
                      ProtobufCBuffer     *buffer);
TonieFCInfo *
       tonie_fcinfo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tonie_fcinfo__free_unpacked
                     (TonieFCInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TonieFreshnessCheckRequest_Closure)
                 (const TonieFreshnessCheckRequest *message,
                  void *closure_data);
typedef void (*TonieFCInfo_Closure)
                 (const TonieFCInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tonie_freshness_check_request__descriptor;
extern const ProtobufCMessageDescriptor tonie_fcinfo__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2drequest_2eproto__INCLUDED */
