/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/toniebox.pb.freshness-check.fc-response.proto */

#ifndef PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2dresponse_2eproto__INCLUDED
#define PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2dresponse_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct TonieFreshnessCheckResponse TonieFreshnessCheckResponse;


/* --- enums --- */


/* --- messages --- */

struct  TonieFreshnessCheckResponse
{
  ProtobufCMessage base;
  size_t n_tonie_marked;
  uint64_t *tonie_marked;
  int32_t field2;
  /*
   * 0-3
   */
  int32_t max_vol_spk;
  /*
   * 1=on, 0=off
   */
  int32_t slap_en;
  /*
   * 1=back-left_forw-right, 0=forw-left_back-right
   */
  int32_t slap_dir;
  int32_t field6;
  /*
   * 0-3
   */
  int32_t max_vol_hdp;
  /*
   * 0=on, 1=off, 2=dimmed
   */
  int32_t led;
};
#define TONIE_FRESHNESS_CHECK_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tonie_freshness_check_response__descriptor) \
, 0,NULL, 0, 0, 0, 0, 0, 0, 0 }


/* TonieFreshnessCheckResponse methods */
void   tonie_freshness_check_response__init
                     (TonieFreshnessCheckResponse         *message);
size_t tonie_freshness_check_response__get_packed_size
                     (const TonieFreshnessCheckResponse   *message);
size_t tonie_freshness_check_response__pack
                     (const TonieFreshnessCheckResponse   *message,
                      uint8_t             *out);
size_t tonie_freshness_check_response__pack_to_buffer
                     (const TonieFreshnessCheckResponse   *message,
                      ProtobufCBuffer     *buffer);
TonieFreshnessCheckResponse *
       tonie_freshness_check_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tonie_freshness_check_response__free_unpacked
                     (TonieFreshnessCheckResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TonieFreshnessCheckResponse_Closure)
                 (const TonieFreshnessCheckResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tonie_freshness_check_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2ftoniebox_2epb_2efreshness_2dcheck_2efc_2dresponse_2eproto__INCLUDED */
