/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/toniebox.pb.taf-header.proto */

#ifndef PROTOBUF_C_proto_2ftoniebox_2epb_2etaf_2dheader_2eproto__INCLUDED
#define PROTOBUF_C_proto_2ftoniebox_2epb_2etaf_2dheader_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _TonieboxAudioFileHeader TonieboxAudioFileHeader;


/* --- enums --- */


/* --- messages --- */

struct  _TonieboxAudioFileHeader
{
  ProtobufCMessage base;
  ProtobufCBinaryData sha1_hash;
  uint64_t num_bytes;
  uint32_t audio_id;
  size_t n_track_page_nums;
  uint32_t *track_page_nums;
  ProtobufCBinaryData _fill;
  /*
   *custom_fields_start
   */
  protobuf_c_boolean has_ogg_granule_position;
  uint64_t ogg_granule_position;
  protobuf_c_boolean has_ogg_packet_count;
  uint64_t ogg_packet_count;
  protobuf_c_boolean has_taf_block_num;
  uint64_t taf_block_num;
  /*
   *custom_fields_end
   */
  protobuf_c_boolean has_pageno;
  uint64_t pageno;
};
#define TONIEBOX_AUDIO_FILE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&toniebox_audio_file_header__descriptor) \
    , {0,NULL}, 0, 0, 0,NULL, {0,NULL}, 0, 0, 0, 0, 0, 0, 0, 0 }


/* TonieboxAudioFileHeader methods */
void   toniebox_audio_file_header__init
                     (TonieboxAudioFileHeader         *message);
size_t toniebox_audio_file_header__get_packed_size
                     (const TonieboxAudioFileHeader   *message);
size_t toniebox_audio_file_header__pack
                     (const TonieboxAudioFileHeader   *message,
                      uint8_t             *out);
size_t toniebox_audio_file_header__pack_to_buffer
                     (const TonieboxAudioFileHeader   *message,
                      ProtobufCBuffer     *buffer);
TonieboxAudioFileHeader *
       toniebox_audio_file_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   toniebox_audio_file_header__free_unpacked
                     (TonieboxAudioFileHeader *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TonieboxAudioFileHeader_Closure)
                 (const TonieboxAudioFileHeader *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor toniebox_audio_file_header__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2ftoniebox_2epb_2etaf_2dheader_2eproto__INCLUDED */
