/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: toniebox.pb.freshness-check.fc-response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "toniebox.pb.freshness-check.fc-response.pb-c.h"
void   tonie_freshness_check_response__init
                     (TonieFreshnessCheckResponse         *message)
{
  static const TonieFreshnessCheckResponse init_value = TONIE_FRESHNESS_CHECK_RESPONSE__INIT;
  *message = init_value;
}
size_t tonie_freshness_check_response__get_packed_size
                     (const TonieFreshnessCheckResponse *message)
{
  assert(message->base.descriptor == &tonie_freshness_check_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tonie_freshness_check_response__pack
                     (const TonieFreshnessCheckResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tonie_freshness_check_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tonie_freshness_check_response__pack_to_buffer
                     (const TonieFreshnessCheckResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tonie_freshness_check_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TonieFreshnessCheckResponse *
       tonie_freshness_check_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TonieFreshnessCheckResponse *)
     protobuf_c_message_unpack (&tonie_freshness_check_response__descriptor,
                                allocator, len, data);
}
void   tonie_freshness_check_response__free_unpacked
                     (TonieFreshnessCheckResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tonie_freshness_check_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tonie_freshness_check_response__field_descriptors[8] =
{
  {
    "tonie_marked",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(TonieFreshnessCheckResponse, n_tonie_marked),
    offsetof(TonieFreshnessCheckResponse, tonie_marked),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, field2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_vol_spk",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, max_vol_spk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slap_en",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, slap_en),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slap_dir",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, slap_dir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field6",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, field6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_vol_hdp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, max_vol_hdp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "led",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TonieFreshnessCheckResponse, led),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tonie_freshness_check_response__field_indices_by_name[] = {
  1,   /* field[1] = field2 */
  5,   /* field[5] = field6 */
  7,   /* field[7] = led */
  6,   /* field[6] = max_vol_hdp */
  2,   /* field[2] = max_vol_spk */
  4,   /* field[4] = slap_dir */
  3,   /* field[3] = slap_en */
  0,   /* field[0] = tonie_marked */
};
static const ProtobufCIntRange tonie_freshness_check_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor tonie_freshness_check_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TonieFreshnessCheckResponse",
  "TonieFreshnessCheckResponse",
  "TonieFreshnessCheckResponse",
  "",
  sizeof(TonieFreshnessCheckResponse),
  8,
  tonie_freshness_check_response__field_descriptors,
  tonie_freshness_check_response__field_indices_by_name,
  1,  tonie_freshness_check_response__number_ranges,
  (ProtobufCMessageInit) tonie_freshness_check_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
