/* tslint:disable */
/* eslint-disable */
/**
 * TeddyCloud API
 * OpenAPI specification for TeddyCloud Backend API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorsErrorsInner } from './ErrorsErrorsInner';
import {
    ErrorsErrorsInnerFromJSON,
    ErrorsErrorsInnerFromJSONTyped,
    ErrorsErrorsInnerToJSON,
} from './ErrorsErrorsInner';

/**
 * Error message container.
 * @export
 * @interface Errors
 */
export interface Errors {
    /**
     * 
     * @type {Array<ErrorsErrorsInner>}
     * @memberof Errors
     */
    errors?: Array<ErrorsErrorsInner>;
}

/**
 * Check if a given object implements the Errors interface.
 */
export function instanceOfErrors(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorsFromJSON(json: any): Errors {
    return ErrorsFromJSONTyped(json, false);
}

export function ErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Errors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : ((json['errors'] as Array<any>).map(ErrorsErrorsInnerFromJSON)),
    };
}

export function ErrorsToJSON(value?: Errors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors === undefined ? undefined : ((value.errors as Array<any>).map(ErrorsErrorsInnerToJSON)),
    };
}

