#ifndef _VERSION_H
#define _VERSION_H

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)


#define BUILD_NAME "TeddyCloud"

#ifndef BUILD_VERSION
#define BUILD_VERSION "vX.X.X"
#endif

#ifndef BUILD_GIT_SHORT_SHA
#define BUILD_GIT_SHORT_SHA "00000000"
#endif

#ifndef BUILD_GIT_SHA
#define BUILD_GIT_SHA "0000000000000000000000000000000000000000"
#endif

#ifndef BUILD_GIT_TAG
#define BUILD_GIT_TAG "unknown"
#endif

#ifndef BUILD_GIT_DATETIME
#define BUILD_GIT_DATETIME "1970-01-01 00:00:00 +0000"
#endif

#if BUILD_GIT_IS_DIRTY == 1
#define BUILD_GIT_DIRTY "-dirty"
#define BUILD_DATETIME BUILD_RAW_DATETIME
#else
#define BUILD_GIT_DIRTY ""
#define BUILD_DATETIME BUILD_GIT_DATETIME
#endif

#define BUILD_FULL_NAME_SHORT BUILD_NAME " " BUILD_VERSION
#define BUILD_LONG_POSTFIX BUILD_DATETIME " " BUILD_OS_ID " " BUILD_PLATFORM "-" BUILD_ARCH "(" BUILD_ARCH_BITS ")"
#define BUILD_FULL_NAME_LONG BUILD_FULL_NAME_SHORT " (" BUILD_GIT_SHORT_SHA BUILD_GIT_DIRTY ") - " BUILD_LONG_POSTFIX
#define BUILD_FULL_NAME_FULL BUILD_FULL_NAME_SHORT " (" BUILD_GIT_SHA BUILD_GIT_DIRTY ") - " BUILD_LONG_POSTFIX " " BUILD_OS

#define WEB_NAME "TeddyCloud Web"

#ifndef WEB_VERSION
#define WEB_VERSION "vX.X.X"
#endif

#ifndef WEB_GIT_SHORT_SHA
#define WEB_GIT_SHORT_SHA "00000000"
#endif

#ifndef WEB_GIT_SHA
#define WEB_GIT_SHA "0000000000000000000000000000000000000000"
#endif

#ifndef WEB_GIT_TAG
#define WEB_GIT_TAG "unknown"
#endif

#ifndef WEB_GIT_DATETIME
#define WEB_GIT_DATETIME "1970-01-01 00:00:00 +0000"
#endif

#if WEB_GIT_IS_DIRTY == 1
#define WEB_GIT_DIRTY "-dirty"
#define WEB_DATETIME WEB_RAW_DATETIME
#else
#define WEB_GIT_DIRTY ""
#define WEB_DATETIME WEB_GIT_DATETIME
#endif

#define WEB_FULL_NAME_SHORT WEB_NAME " " WEB_VERSION
#define WEB_LONG_POSTFIX WEB_DATETIME
#define WEB_FULL_NAME_LONG WEB_FULL_NAME_SHORT " (" WEB_GIT_SHORT_SHA WEB_GIT_DIRTY ") - " WEB_LONG_POSTFIX
#define WEB_FULL_NAME_FULL WEB_FULL_NAME_SHORT " (" WEB_GIT_SHA WEB_GIT_DIRTY ") - " WEB_LONG_POSTFIX

#endif
